### ISSUE TITLE
The bot stops sending message after running for some time 

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bot_monitor#1]
I have forked the code and amended it for gaia-7001. The bot monitor is running at `forbole-sentry-1`. It works right after started. I kept receiving alerts on telegram. However, it stopped sending alerts after running some time. Both the js and Python apps are still running but it’s not sending. Also the resources using is quite high.

**Comment by kwunyeung** [comment]
@sherry13131

**Comment by sherry13131** [comment]
I will try to fix it by sending msg every 15 seconds, see if it fixes the problem, see commit https://github.com/forbole/bot_monitor/commit/7f62ab2c3f97631ba9f7218ec5f491cd0214c566\

**Comment by sherry13131** [comment]
solved by turning them into service, and restart every 15 mins
